export const thesis = {
  id: 3,
  author: "EKA GRADU",
  email: "spam@gmail.com",
  title: "ihminen",
  grader: "Masa",
  grader2: "Pena",
  graderemail: "masa@gmail.com",
  grader2email: "pena@hotmail.com",
  gradertitle: "Professor",
  grader2title: "Assistant Professor",
  urkund: "https://urkund.com/plagioitulol",
  ethesis: "https://ethesis.com/teemu",
  abstract: "Hauki on kala",
  field: "Data science",
  grade: "Approbatur",
  deadline: "29.2.2020",
}

export const theses = [
  {
    id: 2,
    author: "TOKA GRADU",
    email: "matti@gmail.com",
    title: "päällikkö",
    urkund: "http://matti.com",
    ethesis: "https://ethesis.com/matti",
    abstract: "matti on mies",
    grade: "L",
  },
  {
    id: 3,
    author: "KOLMAS GRADU",
    email: "matti@gmail.com",
    title: "päällikkö",
    urkund: "http://matti.com",
    ethesis: "https://ethesis.com/matti",
    abstract: "matti on mies",
    grade: "L",
  },
];
