export const TESTIITEM_GET_ALL_REQUEST = "TESTIITEM_GET_ALL_REQUEST";
export const TESTIITEM_GET_ALL_SUCCESS = "TESTIITEM_GET_ALL_SUCCESS";
export const TESTIITEM_GET_ALL_FAILURE = "TESTIITEM_GET_ALL_FAILURE";

export const TESTIITEM_SAVE_ONE_REQUEST = "TESTIITEM_SAVE_ONE_REQUEST";
export const TESTIITEM_SAVE_ONE_SUCCESS = "TESTIITEM_SAVE_ONE_SUCCESS";
export const TESTIITEM_SAVE_ONE_FAILURE = "TESTIITEM_SAVE_ONE_FAILURE";